import { LanguageCode, Story, StoryParagraph, StorySentence, StoryToken } from '../types';

/**
 * Tabela fonética auxiliar para caracteres chineses mais frequentes (HSK 1-6 + literatura)
 * com marcas diacríticas de tom no padrão Pinyin oficial.
 */
export const CHINESE_PINYIN_MAP: Record<string, string> = {
  // Pronomes e partículas fundamentais
  '我': 'wǒ',
  '你': 'nǐ',
  '他': 'tā',
  '她': 'tā',
  '它': 'tā',
  '们': 'men',
  '的': 'de',
  '地': 'de',
  '得': 'de',
  '了': 'le',
  '着': 'zhe',
  '过': 'guo',
  '在': 'zài',
  '是': 'shì',
  '有': 'yǒu',
  '不': 'bù',
  '没': 'méi',
  '很': 'hěn',
  '这': 'zhè',
  '那': 'nà',
  '哪': 'nǎ',
  '么': 'me',
  '什': 'shén',
  '个': 'gè',
  '只': 'zhǐ',
  '也': 'yě',
  '都': 'dōu',
  '就': 'jiù',
  '还': 'hái',
  '把': 'bǎ',
  '被': 'bèi',
  '给': 'gěi',
  '对': 'duì',
  '从': 'cóng',
  '到': 'dào',
  '和': 'hé',
  '跟': 'gēn',
  '同': 'tóng',
  '与': 'yǔ',
  '为': 'wèi',
  '以': 'yǐ',
  '及': 'jí',

  // Verbos comuns
  '看': 'kàn',
  '见': 'jiàn',
  '听': 'tīng',
  '说': 'shuō',
  '话': 'huà',
  '读': 'dú',
  '写': 'xiě',
  '走': 'zǒu',
  '跑': 'pǎo',
  '来': 'lái',
  '去': 'qù',
  '回': 'huí',
  '出': 'chū',
  '进': 'jìn',
  '起': 'qǐ',
  '坐': 'zuò',
  '站': 'zhàn',
  '躺': 'tǎng',
  '吃': 'chī',
  '喝': 'hē',
  '笑': 'xiào',
  '哭': 'kū',
  '想': 'xiǎng',
  '要': 'yào',
  '爱': 'ài',
  '喜欢': 'xǐhuan',
  '知': 'zhī',
  '道': 'dào',
  '懂': 'dǒng',
  '会': 'huì',
  '能': 'néng',
  '可以': 'kěyǐ',
  '做': 'zuò',
  '作': 'zuò',
  '买': 'mǎi',
  '卖': 'mài',
  '用': 'yòng',
  '问': 'wèn',
  '答': 'dá',
  '教': 'jiāo',
  '学': 'xué',
  '习': 'xí',
  '住': 'zhù',
  '拿': 'ná',
  '放': 'fàng',
  '开': 'kāi',
  '关': 'guān',
  '等': 'děng',
  '带': 'dài',
  '送': 'sòng',
  '穿': 'chuān',
  '脱': 'tuō',
  '找': 'zhǎo',
  '帮': 'bāng',
  '助': 'zhù',
  '成': 'chéng',
  '长': 'zhǎng',
  '变': 'biàn',
  '感': 'gǎn',
  '觉': 'jué',
  '发': 'fā',
  '现': 'xiàn',
  '开端': 'kāiduān',
  '开始': 'kāishǐ',
  '微': 'wēi',

  // Substantivos do cotidiano e natureza
  '人': 'rén',
  '家': 'jiā',
  '天': 'tiān',
  '地球': 'dìqiú',
  '土地': 'tǔdì',
  '日': 'rì',
  '月': 'yuè',
  '年': 'nián',
  '时': 'shí',
  '候': 'hou',
  '分': 'fēn',
  '水': 'shuǐ',
  '火': 'huǒ',
  '山': 'shān',
  '川': 'chuān',
  '河': 'hé',
  '海': 'hǎi',
  '雨': 'yǔ',
  '雪': 'xuě',
  '风': 'fēng',
  '云': 'yún',
  '花': 'huā',
  '草': 'cǎo',
  '木': 'mù',
  '树': 'shù',
  '叶': 'yè',
  '鸟': 'niǎo',
  '鱼': 'yú',
  '茶': 'chá',
  '馆': 'guǎn',
  '店': 'diàn',
  '书': 'shū',
  '字': 'zì',
  '纸': 'zhǐ',
  '笔': 'bǐ',
  '心': 'xīn',
  '情': 'qíng',
  '面': 'miàn',
  '头': 'tóu',
  '手': 'shǒu',
  '眼': 'yǎn',
  '目': 'mù',
  '口': 'kǒu',
  '耳': 'ěr',
  '身': 'shēn',
  '房': 'fáng',
  '间': 'jiān',
  '门': 'mén',
  '窗': 'chuāng',
  '街': 'jiē',
  '路': 'lù',
  '城': 'chéng',
  '市': 'shì',
  '国': 'guó',
  '世': 'shì',
  '界': 'jiè',
  '声': 'shēng',
  '光': 'guāng',
  '色': 'sè',
  '气': 'qì',
  '息': 'xī',
  '事': 'shì',
  '物': 'wù',
  '钱': 'qián',
  '友': 'yǒu',
  '朋': 'péng',
  '师': 'shī',
  '生': 'shēng',
  '老': 'lǎo',
  '少年': 'shàonián',
  '男': 'nán',
  '女': 'nǚ',
  '儿': 'ér',
  '子': 'zǐ',
  '父': 'fù',
  '母': 'mǔ',
  '哥': 'gē',
  '弟': 'dì',
  '姐': 'jiě',
  '妹': 'mèi',
  '夜': 'yè',
  '晨': 'chén',
  '晚': 'wǎn',
  '春': 'chūn',
  '夏': 'xià',
  '秋': 'qiū',
  '冬': 'dōng',
  '桌': 'zhuō',
  '椅': 'yǐ',
  '床': 'chuáng',
  '饭': 'fàn',
  '菜': 'cài',
  '肉': 'ròu',
  '汤': 'tāng',
  '杯': 'bēi',
  '香': 'xiāng',
  '味': 'wèi',
  '音': 'yīn',
  '乐': 'yuè',
  '影': 'yǐng',
  '梦': 'mèng',
  '希': 'xī',
  '望': 'wàng',
  '安': 'ān',
  '静': 'jìng',
  '美': 'měi',
  '好': 'hǎo',
  '明': 'míng',
  '亮': 'liàng',
  '暗': 'àn',
  '高': 'gāo',
  '低': 'dī',
  '大': 'dà',
  '小': 'xiǎo',
  '多': 'duō',
  '少': 'shǎo',
  '远': 'yuǎn',
  '近': 'jìn',
  '快': 'kuài',
  '慢': 'màn',
  '新': 'xīn',
  '旧': 'jiù',
  '热': 'rè',
  '冷': 'lěng',
  '暖': 'nuǎn',
  '温': 'wēn',
  '真': 'zhēn',
  '假': 'jiǎ',
  '难': 'nán',
  '易': 'yì',
  '空': 'kōng',
  '满': 'mǎn',
  '深': 'shēn',
  '浅': 'qiǎn',
  '清': 'qīng',
  '楚': 'chǔ',
  '重': 'zhòng',
  '轻': 'qīng',
  '红': 'hóng',
  '绿': 'lǜ',
  '蓝': 'lán',
  '白': 'bái',
  '黑': 'hēi',
  '黄': 'huáng',
  '金': 'jīn',
  '银': 'yín',

  // Numerais
  '一': 'yī',
  '二': 'èr',
  '三': 'sān',
  '四': 'sì',
  '五': 'wǔ',
  '六': 'liù',
  '七': 'qī',
  '八': 'bā',
  '九': 'jiǔ',
  '十': 'shí',
  '百': 'bǎi',
  '千': 'qiān',
  '万': 'wàn',
  '亿': 'yì',
  '零': 'líng',
  '半': 'bàn',
  '两': 'liǎng',
  '位': 'wèi',

  // Posições
  '上': 'shàng',
  '下': 'xià',
  '左': 'zuǒ',
  '右': 'yòu',
  '前': 'qián',
  '后': 'hòu',
  '里': 'lǐ',
  '外': 'wài',
  '中': 'zhōng',
  '中间': 'zhōngjiān',
  '边': 'biān',
  '旁': 'páng',
  '内': 'nèi',
};

/**
 * Tabela fonética auxiliar para Kanji japoneses frequentes (Furigana em Hiragana)
 */
export const JAPANESE_FURIGANA_MAP: Record<string, string> = {
  '私': 'わたし',
  '僕': 'ぼく',
  '俺': 'おれ',
  '彼': 'かれ',
  '彼女': 'かのじょ',
  '人': 'ひと',
  '男': 'おとこ',
  '女': 'おんな',
  '子': 'こ',
  '子供': 'こども',
  '日': 'ひ',
  '月': 'つき',
  '年': 'とし',
  '時': 'とき',
  '今': 'いま',
  '今日': 'きょう',
  '明日': 'あした',
  '昨日': 'きのう',
  '本': 'ほん',
  '本屋': 'ほんや',
  '家': 'いえ',
  '部屋': 'へや',
  '町': 'まち',
  '道': 'みち',
  '山': 'やま',
  '川': 'かわ',
  '海': 'うみ',
  '空': 'そら',
  '雨': 'あめ',
  '風': 'かぜ',
  '花': 'はな',
  '木': 'き',
  '森': 'もり',
  '水': 'みず',
  '火': 'ひ',
  '光': 'ひかり',
  '朝': 'あさ',
  '昼': 'ひる',
  '夜': 'よる',
  '言': 'こと',
  '話': 'はなし',
  '見': 'み',
  '聞': 'き',
  '行': 'い',
  '来': 'き',
  '食': 'た',
  '飲': 'の',
  '読': 'よ',
  '書': 'か',
  '買': 'か',
  '待': 'ま',
  '歩': 'ある',
  '走': 'はし',
  '好': 'す',
  '大': 'おお',
  '小': 'ちい',
  '新': 'あたら',
  '古': 'ふる',
  '高': 'たか',
  '安': 'やす',
  '長': 'なが',
  '白': 'しろ',
  '黒': 'くろ',
  '赤': 'あか',
  '青': 'あお',
  '茶': 'ちゃ',
  '店': 'みせ',
  '駅': 'えき',
  '友': 'とも',
  '友達': 'ともだち',
  '先生': 'せんせい',
  '学生': 'がくせい',
  '学校': 'がっこう',
  '旅': 'たび',
  '旅行': 'りょこう',
  '心': 'こころ',
  '愛': 'あい',
  '夢': 'ゆめ',
  '希望': 'きぼう',
  '平和': 'へいわ',
  '世界': 'せかい',
  '日本': 'にほん',
  '語': 'ご',
};

/**
 * Retorna a notação fonética (Pinyin ou Furigana) para um token,
 * garantindo cobertura para todas as palavras da história.
 */
export function getAuxiliaryRuby(text: string, language: LanguageCode): string | undefined {
  if (!text) return undefined;
  const trimmed = text.trim();
  if (!trimmed) return undefined;

  // Pontuações comuns não recebem ruby
  if (/^[，。！？、：；“”‘’（）《》·….,!?:;"'()\-— ]+$/.test(trimmed)) {
    return undefined;
  }

  if (language === 'zh') {
    // Busca direta na tabela
    if (CHINESE_PINYIN_MAP[trimmed]) {
      return CHINESE_PINYIN_MAP[trimmed];
    }
    // Se for uma palavra de múltiplos caracteres, tenta compor
    if (trimmed.length > 1) {
      const parts: string[] = [];
      let allFound = true;
      for (const char of trimmed) {
        if (CHINESE_PINYIN_MAP[char]) {
          parts.push(CHINESE_PINYIN_MAP[char]);
        } else {
          allFound = false;
          break;
        }
      }
      if (allFound && parts.length > 0) {
        return parts.join(' ');
      }
    }
  } else if (language === 'ja') {
    if (JAPANESE_FURIGANA_MAP[trimmed]) {
      return JAPANESE_FURIGANA_MAP[trimmed];
    }
  }

  return undefined;
}

/**
 * Percorre uma história completa e injeta ruby em todos os tokens
 * que ainda não o possuam para línguas com suporte fonético (zh, ja).
 */
export function enrichStoryPhonetics(story: Story): Story {
  if (!story || (story.language !== 'zh' && story.language !== 'ja')) {
    return story;
  }

  const enrichedParagraphs: StoryParagraph[] = (story.paragraphs || []).map((p) => ({
    ...p,
    sentences: (p.sentences || []).map((s: StorySentence) => ({
      ...s,
      tokens: (s.tokens || []).map((t: StoryToken) => {
        if (t.ruby) return t;
        const aux = getAuxiliaryRuby(t.text, story.language);
        return aux ? { ...t, ruby: aux } : t;
      }),
    })),
  }));

  return {
    ...story,
    paragraphs: enrichedParagraphs,
  };
}
